limits:
  member:
    ip: 2
    name: 2
  admin:
    ip: 1
    name: 1
throddle: 5
messages:
  whitelist: 'You are not whitelisted'
  max:
    ip: 'Too many IPs used'
    name: 'Too many names used'
protection:
  ip: true
fake-online: true
startup:
  whitelist: false