limits:
  member:
    ip: 2
    name: 2
  admin:
    ip: 1
    name: 1
throddle: 5
messages:
  whitelist: 'You are not whitelisted'
  max:
    ip: 'Too many IPs used'
    name: 'Too many names used'
protection:
  ip: true
startup:
  whitelist: false
version: 2.0.6
encryption: md5
mysql:
  enable: false
  host: localhost
  port: 3666
  user: root
  pass: password
  db: database