name: AntiMulti
main: com.lordralex.antimulti.AntiMulti
version: 2.0.1
author: Lord_Ralex
description: AntiMulti- Prevents IP sharing to put it bluntly
categories: [ADMIN]
commands:
    am:
        description: 'Access the commands of AntiMulti'
        permission: antimulti.cmd
        aliases: [antimulti]
    getIPs:
        description: 'Get peoples ips they have used'
        permission: antimulti.cmd.getIPs
    getNames:
        description: 'Get the names from an ip'
        permission: antimulti.cmd.getNames
    add:
        description: 'Add a player'
        permission: antimulti.cmd.add
    whitelist:
        description: 'Use the AM whitelist'
        permission: antimulti.cmd.whitelist
    banall:
        description: 'Ban a bunch of folks'
        permission: antimulti.cmd.banall
    login:
        description: 'Log in to the server'
        permission: antimulti.login
    register:
        description: 'Register your player'
        permission: antimulti.register
permissions:
    antimulti.*:
        description: Gives all nodes for Anti-Multi
        default: op
        children:
            antimulti.whitelist: true
            antimulti.notify: true
            antimulti.forceRegister: true
            antimulti.cmd: true
            antimulti.cmd.add: true
            antimulti.cmd.whitelist: true
            antimulti.cmd.banall: true
            antimulti.cmd.getNames: true
            antimulti.cmd.getIPs: true
            antimulti.register: true
            antimulti.login: true
    antimulti.whitelist:
        description: Allows player to login to server with AM whitelist on
        default: op
    antimulti.cmd:
        description: Access to /am
        default: op
        command: "/am"
    antimulti.cmd.add:
        description: Adds a player to the bypass
        default: op
        command: "/am add Lord_Ralex 1.2.3.4 (pword) (pword)"
    antimulti.cmd.whitelist:
        description: Toggles the whitelist
        default: op
        command: "/am whitelist"
    antimulti.cmd.banall:
        description: Bans a bunch of people
        default: op
        command: "/banall <name>"
    antimulti.cmd.getNames:
        description: Get some names
        default: op
        command: "/getNames <ip>"
    antimulti.cmd.getIPs:
        description: Get some IPs
        default: op
        command: "/getIPs <name>"
    antimulti.register:
        description: Lets a player register
        default: true
    antimulti.login:
        default: true
        description: Lets a player login
    antimulti.forceRegister:
        default: op
        description: Forces a player to register